### ISSUE TITLE
Redo PR #52 but with `bottleneck.nanmean`

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/open-estimate#53]
Inspired by @delgadom to retry the performance fix in PR #52 but using `bottleneck.nanmean`.

Be sure to test downstream and profile labor projection to see what improves.

https://github.com/ClimateImpactLab/risingverse/pull/7 needs to clear first.

Need to add `bottleneck` to package requirements. Consider making it optional...?

**Comment by delgadom** [comment]
Thank you!!! sorry for missing the bottleneck dependency the first time around. Big fan of not making that optional if we can get away with it.

On this note, I didn't realize that explicitly using bottleneck was preferable to numpy. [xarray seems to magic this all away](https://github.com/pydata/xarray/blob/4aa7622b6ff16647df64fe69f39438b7cbe9576c/xarray/core/nputils.py) for you but this is a great tip - thanks!

**Comment by brews** [comment]
@delgadom Normally I'd say that `numpy` is a fine default and people shouldn't add another compiled dependency without very good reason.

In this case, I profiled a projection and found that this one case of `sum` was called 35,315,832 times and was taking over 70% of run-time. Being called 35 million times in something is a pretty reason to consider C/C++/LLVM compiled packages or writing our solution.

I *think* Stephan Hoyer also came up with the `numbagg` package, which is LLVM-compiled (via `numba`) and it can be even faster than `bottleneck` but it looks like that's not as mature/well supported. Something to keep an eye on, though.

The other thing to consider is that these are not python objects so their memory needs are clearly defined and they can run without the GIL - which is an _awesome_ feature for distributed high-performance computing (e.g. via `dask`).

Sorry to geek out on you. I get pumped about this stuff.
